export const MESSAGE = {
    WARNING: {
        ROLE_NOT_FOUND: 'Role not found',
        USER_NOT_FOUND: 'User not found',
        EMAIL_ALREADY_EXISTS: 'Email already exists',
        PERMISSION_NOT_FOUND: 'Permission not found',
        INVALID_CREDENTIALS: 'Invalid credentials',
        EVENT_CATEGORY_NOT_FOUND: 'Event category not found',
        EVENT_CATEGORY_EXIST: 'Event category already exists',
        HALL_ALREADY_EXIST: 'Hall already exists',
        HALL_NOT_FOUND: 'Hall not found',
        PACKAGE_ALREADY_EXISTS: 'Package already exists',
        PACKAGE_NOT_FOUND: 'Package not found',
        ADDITIONAL_SERVICE_EXISTS: 'Additional service already exists',
        ADDITIONAL_SERVICE_NOT_FOUND: 'Additional service not found',
        DISCOUNT_CODE_ALREADY_EXIST: 'Discount Code already exists',
        DISCOUNT_NOT_FOUND: 'Discount not found',
        MENU_GROUP_ALREADY_EXISTS: 'Menu group already exists',
        MENU_GROUP_NOT_FOUND: 'Menu group not found',
        MENU_CATEGORY_ALREADY_EXISTS: 'Menu category already exists',
        MENU_CATEGORY_NOT_FOUND: 'Menu category not found',
    },
    SUCCESS: {
        ROLE_CREATED: 'Role created successfully',
        USER_CREATED: 'User created successfully',
        PERMISSION_CREATED: 'Permission created successfully',
        USER_LOGIN: 'User login successfully',
        USER_ROLE_UPDATED: 'User role updated successfully',
        USERS_FETCHED: 'Users fetched successfully',
        PERMISSIONS_FETCHED: 'Permissions fetched successfully',
        ROLE_FETCHED: 'Role fetched successfully',
        ALL_PERMISSIONS_FETCHED: 'All permissions fetched successfully',
        ALL_ROLES_FETCHED: 'All roles fetched successfully',
        ROLE_PERMISSIONS_UPDATED: 'Role permissions updated successfully',
        EVENT_CATEGORY_CREATED: 'Event category created successfully',
        EVENT_CATEGORIES_FETCHED: 'Event categories fetched successfully',
        EVENT_CATEGORY_UPDATED: 'Event category updated successfully',
        EVENT_CATEGORY_DELETED: 'Event category deleted successfully',
        HALL_ADDED: 'Hall added successfully',
        ALL_HALLS_FETCHED: 'All halls fetched successfully',
        HALL_FETCHED: 'Hall fetched successfully',
        HALL_UPDATED: 'Hall updated successfully',
        HALL_DELETED: 'Hall deleted successfully',
        PACKAGE_ADDED: 'Package added successfully',
        PACKAGES_FETCHED: 'Packages fetched successfully',
        PACKAGE_UPDATED: 'Package updated successfully',
        PACKAGE_DELETED : 'Package deleted successfully',
        PACKAGE_FETCHED: 'Package fetched successfully',
        ADDITIONAL_SERVICE_ADDED: 'Additional service added successfully',
        ADDITIONAL_SERVICES_FETCHED: 'Additional services fetched successfully',
        ADDITIONAL_SERVICE_FETCHED: 'Additional service fetched successfully',
        ADDITIONAL_SERVICE_UPDATED: 'Additional service updated successfully',
        ADDITIONAL_SERVICE_DELETED: 'Additional service deleted successfully',
        DISCOUNT_CREATED: 'Discount created successfully',
        ALL_DISCOUNTS_FETCHED: 'All discounts fetched successfully',
        DISCOUNT_FETCHED: 'Discount fetched successfully',
        DISCOUNT_UPDATED: 'Discount updated successfully',
        DISCOUNT_DELETED: 'Discount deleted successfully',
        MENU_GROUP_ADDED: 'Menu group added successfully',
        MENU_GROUPS_FETCHED: 'Menu groups fetched successfully',
        MENU_GROUP_FETCHED: 'Menu group fetched successfully',
        MENU_GROUP_UPDATED: 'Menu group updated successfully',
        MENU_GROUP_DELETED: 'Menu group deleted successfully',
        MENU_CATEGORY_ADDED: 'Menu category added successfully',
        MENU_CATEGORIES_FETCHED: 'Menu categories fetched successfully',
        MENU_CATEGORY_FETCHED: 'Menu category fetched successfully',
        MENU_CATEGORY_UPDATED: 'Menu category updated successfully',
        MENU_CATEGORY_DELETED: 'Menu category deleted successfully',

    }
}       